[root]
url = "/"
name = "Home"

[[root.children]]
name = "Services"
url = "/services.html"
documentId = "1cJ-QAuUsQnZW79-Z6O_GDjHxj1h6cmErJhBWEVppnyc"

[[root.children.children]]
name = "Consulting"
url = "/consulting.html"
documentId = "1FaG4GHOFwc-rsu-OrbPK_H2-Iw5icl6BuEa27vCc--U"

[[root.children.children]]
name = "Operations"
url = "/operations.html"
documentId = "1tzO_LgHnKjwEeFphTXCpJtHHjR16P_t4xX3AHO9yLz0"

[[root.children.children]]
name = "Content / PIM / Syndication"
url = "/syndication.html"

[[root.children.children]]
name = "Advertising"
url = "/advertising.html"
documentId = "1EKmhVIEPG3_q5jQe07-SXjRv-4sasIuz1GFBLQXzkaQ"

[[root.children.children]]
name = "Website Creation"
url = "/website-creation.html"
documentId = "1xK8C26VriFVWI6qTmQ5y4P0RUMBvRA7Y3Ii7vJkDvUI"

[[root.children.children]]
name = "Analytics"
url = "/analytics.html"
documentId = "1XB3ohTRBlwPyGu_o3UGN7e-83HUqP8IEtnN_3u_twP0"

[[root.children.children.children]]
name = "Profitero"
url = "/profitero.html"

[[root.children.children.children]]
name = "Reveals"
url = "/reveals.html"

[[root.children]]
name = "Salsify"
url = "/salsify.html"

[[root.children]]
name = "Shopify"
url = "/website-creation.html#shopify"

[[root.children]]
name = "About us"
url = "/about-us.html"
documentId = "1kR_twkG_m5S0My5olwbJSam27tHoUIdQSv_GQcybbl8"

[[root.children.children]]
name = "Team"
url = "/our-team.html"

[[root.children.children]]
name = "Testimonials"
url = "/testimonials.html"
documentId = "1L_arP-U9Dl0QuaF2U_OB5Zt_ibcQfPuLXYk0KCAkqoM"


[[root.children]]
name = "Resources"
url = "/resources.html"

[[root.children.children]]
name = "Blog"
url = "/news.html"

[[root.children.children.children]]
name = "{{ page.title }}"
url = "/_layouts/blog.html"

[[root.children.children]]
name = "Podcast"
url = "/podcast.html"

[[root.children.children]]
name = "Webinars"
url = "/webinar.html"

[[root.children.children]]
name = "White paper"
url = "/white-paper-form.html"

[[root.children.children]]
name = "Case studies"
url = "/case-studies.html"

# [[root.children.children]]
# name = "Partners"
# url = "/partners.html"

[[root.children]]
name = "Contact us"
url = "/contact.html"
