[root]
url = "/"
name = "Home"

[[root.children]]
name = "Services"
url = "/services.html"

[[root.children.children]]
name = "Consulting"
url = "/consulting.html"
documentId = "1FaG4GHOFwc-rsu-OrbPK_H2-Iw5icl6BuEa27vCc--U"

[[root.children.children]]
name = "Account management"
url = "/account-management.html"

[[root.children.children]]
name = "Advertising"
url = "/advertising.html"
documentId = "1EKmhVIEPG3_q5jQe07-SXjRv-4sasIuz1GFBLQXzkaQ"

[[root.children.children]]
name = "Syndication"
url = "/syndication.html"

[[root.children.children]]
name = "Shopify"
url = "/shopify.html"

[[root.children.children]]
name = "Profitero"
url = "/profitero.html"

[[root.children]]
name = "Salsify"
url = "/syndication.html#salsify"

[[root.children]]
name = "Shopify"
url = "/shopify.html"

[[root.children]]
name = "About us"
url = "/about-us.html"
documentId = "1kR_twkG_m5S0My5olwbJSam27tHoUIdQSv_GQcybbl8"

[[root.children.children]]
name = "Team"
url = "/our-team.html"

[[root.children.children]]
name = "Testimonials"
url = "/testimonials.html"

[[root.children.children]]
name = "Blog"
url = "/news.html"

[[root.children]]
name = "Ressources"
url = "/ressources.html"

[[root.children.children]]
name = "Webinar"
url = "/webinar.html"

[[root.children.children]]
name = "Podcast"
url = "/podcast.html"

[[root.children.children]]
name = "White paper"
url = "/white-paper-form.html"

[[root.children.children]]
name = "Partners"
url = "/partners.html"

[[root.children]]
name = "Contact us"
url = "/contact.html"
