[root]
url = "/"
name = "Home"

[[root.children]]
name = "Services"
# url = "/services.html"

[[root.children.children]]
name = "Global Expansion"
url = "/global-expansion.html"

[[root.children.children]]
name = "Retail Media"
url = "/retail-media.html"

[[root.children.children]]
name = "Data & Technology"
url = "/data-and-tech.html"

# [[root.children.children]]
# name = "Content & Creative"
# url = "/syndication.html"

[[root.children.children]]
name = "Content Syndication"
url = "/salsify.html"

[[root.children.children]]
name = "Website Creation"
url = "/website-creation.html"

[[root.children]]
name = "About us"
# url = "/about-us.html"


[[root.children.children]]
name = "Company"
url = "/about-us.html"

[[root.children.children]]
name = "Our Team"
url = "/our-team.html"

[[root.children.children]]
name = "Partners"
url = "/partners.html"

# [[root.children.children]]
# name = "Careers"
# url = "about:blank"

[[root.children]]
name = "Resources"
# url = "/resources.html"

[[root.children.children]]
name = "Blog & news"
url = "/news.html"

[[root.children.children]]
name = "Webinars"
url = "/webinar.html"

[[root.children.children]]
name = "Case studies"
url = "/case-studies.html"

[[root.children.children]]
name = "White paper"
url = "/white-paper-form.html"

[[root.children.children]]
name = "Podcast"
url = "/podcast.html"

[[root.children]]
name = "Client Login"
url = "/clientlogin.html"

[[root.children]]
name = "Contact us"
url = "/contact.html"
