__use_generic_keys__ = { url = "socialNetwork" }

team_order = [
  "Consulting",
  "Account management",
  "Retail",
  "DSP team",
  "Analytics team",
  "Administration team",
]

[CEO]
email = "j.deguigne@e-comas.com"
Name = "Jérôme de Guigné"
Title = "Founder & CEO"
bio = """\
    Jérôme specialises in helping global brands grow their distribution on \
    and through Amazon. His wealth of ecommerce expertise comes from 20 years \
    of sales and international distribution experience in Europe, Asia and \
    North America. Jérôme focuses on real-world proven solutions, with \
    results as great as multiplying revenue by five times or more within two \
    years.\
  """
pictureUrl = "/images/team/jerome.png"
url.LinkedIn = "https://www.linkedin.com/in/jeromedeguigneamazonexpert/"
url.Medium = "https://medium.com/@Amazon_expert"
url.YouTube = "https://www.youtube.com/channel/UC8FEB3vsicxo5gI3mtdl50A"

[COO]
Name = "Amalia Sebakunzi"
Title = "Chief Operating Officer"
bio = """\
    Amalia is a business leader with over 14 years of international experience \
    spanning a broad range of industries, including FMCG, Food, Beauty, \
    Luxury, Ecommerce and Digital Health. Amalia joined e-Comas as Chief \
    Operating Officer in 2021, having worked in Nigeria for three years \
    heading up strategic marketing activities for one of the world’s leading \
    food brands. With over a decade of sales and marketing expertise, Amalia \
    has a wealth of knowledge to help brands succeed on all online \
    marketplaces.\n\
  """
quote = "\"Any business not investing time & ressources on e-commerce right now is missing out on the opportunity of the century\""
pictureUrl = "/images/team/amalia.png"
url.LinkedIn = "https://www.linkedin.com/in/amaliawidder/"
url.YouTube = "https://www.youtube.com/watch?v=0-TBc8-UC1w"


[[team_member]]
Name = "Nazlı Kayıkç"
Title = "Head of Consulting"
Team = "Consulting"
quote = "Identifying your gaps and needs at the beginning of your ecom journey is the greatest favor that you can do for your brand'"
pictureUrl = "/images/team/Nazli.png"
url.LinkedIn = "https://www.linkedin.com/in/nazl%C4%B1-ipek-kay%C4%B1k%C3%A7%C4%B1-86644a23/"
url.YouTube = "https://www.youtube.com/watch?v=nN8QWZ5S7-M"


[[team_member]]
Name = "Agu\u00e8ne Sambou"
Title = "Salsify Project Manager"
Team = "Consulting"
quote = "\"Whithout challenge, There Isn't Change\""
pictureUrl = "/images/team/aguene.png"


[[team_member]]
Name = "Claudiu Clement"
Title = "Senior Consultant / Salsify Expert"
Team = "Consulting"
quote = "\"Building a great experience for the right client is the main driver of success in ecommerce.\""
pictureUrl = "/images/team/Claudiu-Clement.png"
url.LinkedIn = "https://www.linkedin.com/in/claudiu-clement/"
url.YouTube = "https://www.youtube.com/watch?v=LgI0R1hmyCE&ab_channel=e-Comas"


[[team_member]]
Name = "Antonio Vicedo Mart\u00ednez"
Title = "Senior Consultant / Salsify Expert"
Team = "Consulting"
quote = "\"In a world that moves and evolves as fast as e-commerce, make sure to save some time to reflect and plan\""
pictureUrl = "/images/team/Antonio-VM.png"
url.LinkedIn = "https://www.linkedin.com/in/antoniovicedo/"


[[team_member]]
Name = "Nagapooja Ramesh"
Title = "Salsify Support"
Team = "Consulting"
quote = "\"When we really pay attention,everything is your teacher.\""
pictureUrl = "/images/team/Pooja.png"
url.LinkedIn = "www.linkedin.com/in/nagapooja-ramesh-a77850136"


[[team_member]]
Name = "Sarra Maatallah"
Title = "Senior Account Management & Team lead"
Team = "Account management"
priority = 2
quote = "'I always believe that the work you deliever is an extension of yourself. Care about the way you want your work performance to be look at the same way you care about your own image. Quality, passion and care should  be what define you. This is my own recipe to success.''"
pictureUrl = "/images/team/Sarah.png"
url.LinkedIn = "https://www.linkedin.com/in/sarramaatallah-amazonexpert"


[[team_member]]
Name = "Richard Ravichandar"
Title = "Senior Account Manager"
Team = "Account management"
quote = "We CARE for your business like no one else did. We GROW your business like never before."
pictureUrl = "/images/team/Richard.png"
url.LinkedIn = "https://www.linkedin.com/in/richard-ravichandar-a1929a50/"


[[team_member]]
Name = "Riley Bell"
Title = "Senior Account Manager"
Team = "Account management"
quote = "\"eCommerce is an ever evolving landscape with fresh challenges and new opportunities emerging each day\""
pictureUrl = "/images/team/Riley-.png"
url.LinkedIn = "https://www.linkedin.com/in/bellriley/"
url.YouTube = "https://www.youtube.com/watch?v=miLaUlqNruc"


[[team_member]]
Name = "Raichel Rajan"
Title = "Account Support"
Team = "Account management"
quote = "\"Success is not a one time life achievement. Success is a habit\""
pictureUrl = "/images/team/Raichel.png"
url.LinkedIn = "linkedin.com/in/raichel-rajan-34a894b9"


[[team_member]]
Name = "Navya Aravindakshan"
Title = "Account Support"
Team = "Account management"
quote = "Discover something new. Discover something different."
pictureUrl = "/images/team/Navya.png"
url.LinkedIn = "https://www.linkedin.com/in/navya-aravindakshan/"
url.YouTube = "https://www.youtube.com/watch?v=IL8xeEXZIzI"


[[team_member]]
Name = "Manu Mathew"
Title = "Account Support"
Team = "Account management"
quote = "Alone we can do so little, together we can do so much"
pictureUrl = "/images/team/Manu.png"
url.LinkedIn = "https://www.linkedin.com/in/manujoymathew"
url.YouTube = "https://www.youtube.com/watch?v=37Q_2Ta4BRY"


[[team_member]]
Name = "Carlos De Almeida"
Title = "Senior Account Management & Team lead"
Team = "Account management"
priority = 1
quote = "\"Care is the key of any successful business partnership\""
pictureUrl = "/images/team/Carlos.png"
url.LinkedIn = "https://www.linkedin.com/in/carlos-de-almeida-amazonexpert/"


[[team_member]]
Name = "Whitney LUPTER"
Title = "Senior Account Manager"
Team = "Account management"
quote = "\"If Amazon offers something for free, take advantage of it.\""
pictureUrl = "/images/team/Whitney.png"
url.LinkedIn = "https://www.linkedin.com/in/lupterwithney/"
url.YouTube = "https://www.youtube.com/watch?v=IvLMNwh9z70"


[[team_member]]
Name = "Ang\u00e9lica L\u00f3pez"
Title = "Account Manager"
Team = "Account management"
quote = "\"Who is not able to adapt to the constant changes is out of the game\""
pictureUrl = "/images/team/Angelica.png"
url.LinkedIn = "https://www.linkedin.com/in/angelicalopez8661/"


[[team_member]]
Name = "Henintsoa Andriatianarivo"
Title = "Account Support"
Team = "Account management"
quote = "\"A smooth sea never made a skilled sailor.\""
pictureUrl = "/images/team/Henintsoa.png"
url.LinkedIn = "https://www.linkedin.com/in/henintsoa/"
url.YouTube = "https://www.youtube.com/watch?v=rmB-6-x9spA"


[[team_member]]
Name = "Mireille Rasoa"
Title = "Account Support"
Team = "Account management"
quote = "\"You are your only limit\""
pictureUrl = "/images/team/Mireille.png"
url.LinkedIn = "https://www.linkedin.com/in/mireille-rasoa-605194215/"


[[team_member]]
Name = "Monika Palagiri"
Title = "Account Support"
Team = "Account management"
quote = "\"The way to smooth,efficient & successful business is attention to little details\""
pictureUrl = "/images/team/Monika.png"
url.LinkedIn = "https://www.linkedin.com/in/monika-palagiri-67711bb2"
url.YouTube = "https://www.youtube.com/watch?v=GvEk-ZTJka4"


[[team_member]]
Name = "Yann Randrianasolo"
Title = "Account Support"
Team = "Account management"
quote = "\"Per aspera ad astra\""
pictureUrl = "/images/team/Yann.png"
url.LinkedIn = "https://www.linkedin.com/in/yann-randrianasolo-aa3090198/"


[[team_member]]
Name = "Seval Andic"
Title = "Senior Account Management & Team lead"
Team = "Account management"
priority = 1
quote = "The ability to adapt is the main ingredient behind succesful growth recipes."
pictureUrl = "/images/team/sevel.png"
url.LinkedIn = "https://www.linkedin.com/in/sevalsolmaz/"
url.YouTube = "https://www.youtube.com/watch?v=1lhz5W6uTUs"


[[team_member]]
Name = "Charl\u00e8ne Gr\u00e9goire"
Title = "Senior Account Manager"
Team = "Account management"
quote = "\"Every problem is a gift - without problems we would not grow\""
pictureUrl = "/images/team/Charlene.png"
url.LinkedIn = "www.linkedin.com/in/charlene-gregoire"
url.YouTube = "https://www.youtube.com/watch?v=DTdtGuAuY6E"


[[team_member]]
Name = "Claire Guilleautot"
Title = "Account manager"
Team = "Account management"
quote = "Details create the big picture."
pictureUrl = "/images/team/Claire.png"
url.LinkedIn = "https://www.linkedin.com/in/claire-guilleautot-0347b8172/"


[[team_member]]
Name = "Elvis Kisekka"
Title = "Account Manager"
Team = "Account management"
quote = "\"The secret to success is to do the common things uncommonly well.\""
pictureUrl = "/images/team/Elvis.png"
url.LinkedIn = "https://www.linkedin.com/in/elviskisekka/"


[[team_member]]
Name = "Asha Upadhya"
Title = "Support Account Manager"
Team = "Account management"
quote = "Do not underestimate the power of 'Word of Mouth\"Give your customers something Wonderful to talk about and they will do the rest"
pictureUrl = "/images/team/Asha-Upadhya.png"
url.LinkedIn = "https://www.linkedin.com/in/asha-upadhya-6781a6108/"
url.YouTube = "https://www.youtube.com/watch?v=rHKvKtK4dsI"


[[team_member]]
Name = "Yohann Paul"
Title = "Account Support"
Team = "Account management"
quote = "\"There is a superhero in all of us, We just need the courage to put on the cape.\""
pictureUrl = "/images/team/Yohan.png"
url.LinkedIn = "https://www.linkedin.com/in/yohannpaul/"


[[team_member]]
Name = "Sven Jacosben Diaz"
Title = "Account Support"
Team = "Account management"
quote = "You miss 100% of the shots you don't take"
pictureUrl = "/images/team/Sven.png"
url.LinkedIn = "https://www.linkedin.com/in/sven-jacobsen-diaz/"


[[team_member]]
Name = "Tomas Nehera"
Title = "Head of Retail"
Team = "Retail"
quote = "\"It doesnt matter who we are , what matters is our dedication and plan\""
pictureUrl = "/images/team/Tomas.png"
url.LinkedIn = "https://www.linkedin.com/in/tomasnehera-amazonexpert/"


[[team_member]]
Name = "Beatrice Senese"
Title = "Senior Account Manager"
Team = "Retail"
quote = "\"The best place to hide a corpse after a passion crime? The second page of search on Amazon, of course.\""
pictureUrl = "/images/team/Beatrice-Senese.png"


[[team_member]]
Name = "Arjun Narayan"
Title = "Account Support"
Team = "Retail"
quote = "The key to success is to concentrate on GOALS, not OBSTACLES."
pictureUrl = "/images/team/Arjun.png"


[[team_member]]
Name = "Joel Young"
Title = "Lead Creative"
Team = "Content Team"
quote = "Be happy in everything you do. That's most important. And give a pet a home."
pictureUrl = "/images/team/Joel.png"


[[team_member]]
Name = "Jessica Barton"
Title = "Social & Copywriting Manager"
Team = "Content Team"
quote = ""
pictureUrl = "/images/team/Jessica-Barton-.png"


[[team_member]]
Name = "Jessamy Chapman"
Title = "Press Manager"
Team = "Content Team"
quote = ""
pictureUrl = "/images/team/Jessamy-Chapman.png"


[[team_member]]
Name = "Dheeraj Chawla"
Title = "DSP Expert"
Team = "DSP team"
quote = "\u201cThe modern marketer is an experimenter, a lover of data, a content creator, a justifier of ROI\u201d"
pictureUrl = "/images/team/Dheeraj-Chawla.png"
url.LinkedIn = "https://www.linkedin.com/in/dheerajchawla1/"


[[team_member]]
Name = "David Recchia"
Title = "Head of Analytics"
Team = "Analytics team"
quote = "\"Working with e-Comas, we can help brands leverage the real potential of their data\""
pictureUrl = "/images/team/David-Recchia.png"
url.LinkedIn = "https://www.linkedin.com/in/david-recchia-42744820/"


[[team_member]]
Name = "Julien Soyer"
Title = "Senior Data analyst"
Team = "Analytics team"
quote = "\u201cGiving up is the only sure way to fail.\u201d - Gena Showalter"
pictureUrl = "/images/team/Julien-Soyer-.png"
url.LinkedIn = "https://www.linkedin.com/in/julien-s-36837891/"


[[team_member]]
Name = "Paul Mordant"
Title = "Data Scientist Consultant"
Team = "Analytics team"
quote = "\"What gets measured, gets managed\""
pictureUrl = "/images/team/Paul.png"
url.LinkedIn = "https://www.linkedin.com/in/paul-mordant-a5445917a/"


[[team_member]]
Name = "Alexandre Zambeaux"
Title = "Senior Business Development Manager"
Team = "Business Development & marketing team"
quote = "\u201cKnow the rules well, so you can break them effectively.\u201d"
pictureUrl = "/images/team/Alexandre-Zambeaux.png"
url.LinkedIn = "https://www.linkedin.com/in/alexandrezambeaux/"
url.YouTube = "https://www.youtube.com/watch?v=lW1ffcwiyP8"


[[team_member]]
Name = "Christel Bordoni"
Title = "Marketing and Business Development Manager"
Team = "Business Development & marketing team"
quote = "\" Offer an omnichannel experience to your customer is the future of e-commerce \""
pictureUrl = "/images/team/christel.png"
url.LinkedIn = "https://www.linkedin.com/in/c-bordoni-amazonspecialist/"


[[team_member]]
Name = "Sneha Shriyan"
Title = "Business Development Manager"
Team = "Business Development & marketing team"
quote = "\"Pandemic or no pandemic, e-commerce will keep your business growing\""
pictureUrl = "/images/team/Sneha-Shriyan.png"


[[team_member]]
Name = "Karolina M'besso"
Title = "Head of Admin"
Team = "Administration team"
quote = "\"It is not for us to forecast the future, but to shape it\", AS Exup\u00e9ry"
pictureUrl = "/images/team/Karo.png"
url.LinkedIn = "https://www.linkedin.com/in/karol%C3%ADna-m-besso-70172b35/"


[[team_member]]
Name = "Oscar Samson"
Title = "India Team lead"
Team = "Administration team"
quote = "Success is the sum of small efforts repeated day in and day out"
pictureUrl = "/images/team/Oscar.png"
url.LinkedIn = "www.linkedin.com/in/oscar-samson"


[[team_member]]
Name = "Misa Manass\u00e9"
Title = "Office Manager"
Team = "Administration team"
quote = "\"Persistence is the path to success\" C Chaplin"
pictureUrl = "/images/team/Misa.png"
