[[item]]
text = """\
    We have worked with e-Comas's consulting services team to help us define \
    our global Amazon approach for our bicycle tyres business line. They \
    quickly adapted their in-depth and hands-on knowledge of the Amazon \
    platform and ways to our business context. We saved a great amount of time \
    and above all, it helped us have a clearer view and align internally to \
    revamp our approach.\
  """
name = "Cédric Couture"
title = "Global eRetail Manager Bicycle Tyres"
company = "Michelin"
image = "/images/cederic-couture.jpg"
logo = "/images/michelin.svg"


[[item]]
text = """\
    We've worked with the e-Comas team since December of 2019 and have seen \
    our monthly sales revenue increase by more than 10x. Besides growing our \
    sales, they've helped us gain better control of our presence on Amazon, \
    and are effectively launching us in the American and other global \
    marketplaces.\
  """
name = "Amanda Jenner"
title = "Founder and Director"
company = "My Carry Potty"
image = "/images/Amanda Jenner.jpg"
logo = "/images/my-carry-potty.png"


# [[item]]
# text = """\
#     Jérôme and e-Comas are brilliant door openers, they know everybody in \
#     Amazon. They are very concentrated on growth strategies and delivering on \
#     targets. Jerôme is a very good salesperson and a brilliant speaker, \
#     supported by a hard-working team.\
#   """
# name = "Markus Anacker"
# title = "Executive Vice President at Eschenbach"
# company = "Eschenbach"
# # image = "https://media.licdn.com/dms/image/C4D03AQGtvsYJlg9DRg/profile-displayphoto-shrink_200_200/0?e=1579132800&v=beta&t=YDDpHQ9muS-Dq1IN9u2JOMVw7vc2LsiYkTX_ZcdLDLM"
# # logo = "/images/eschenbach.gif"
# logo = "/images/my-carry-potty.png"


[[item]]
text = """\
    We more than doubled our sales, which was a better turn rate than the \
    other channels at the time. We had better control of our listings and an \
    overall better brand presence. A good clean-up project that helped scale \
    up our company.\
  """
name = "Oliver Amdrup"
title = "Founder"
company = "Puori"
image = "/images/oliver-amdrup.jpg"
logo = "/images/brands/puori.svg"


[[item]]
text = """\
    Working with my e-Comas team, especially Seval and Claire, has been easy \
    and effortless. Through their efforts on our Vendor Account, we've seen \
    the best Amazon performance across our European sales channels. We look \
    forward to expanding our collaboration!\
  """
name = "Frits Kuper"
title = "Director of International Sales"
company = "Superfeet"
image = "/images/frits-kuper.jpg"
logo = "/images/superfeet.png"

[[item]]
text = """\
    e-Comas has helped us define our strategy on Amazon in Europe, and our \
    expansion plans. The team have helped us navigate the challenges of \
    Amazon, handled our account in all Europe and bring our brand to a strong \
    position on Amazon in terms of branding and sales, making of e-Commerce a \
    strong growth of our business in Europe.\n\
  """
name = "Lidia Santos"
title = "Senior MarCom & eCommerce Manager"
company = "Sunstar Europe"
image = "/images/lidia-santos.jpg"
logo = "/images/brands/sunstar.svg"

[[item]]
text = """\
    This e-Commerce strategy and branding workshop was perfectly conducted.\n\
    \n\
    You asked the right questions and gave us the opportunity to find a \
    setting of open and future oriented conversation paired with \
    professionalism and wit.\
  """
name = "Tristan Brockelmanns"
title = "Chief Commercial Officer"
company = "Stebler"
image = "/images/tristan-brockelmanns.jpg"
logo = "/images/brands/stebler.png"

[[item]]
text = """\
    A very structured workshop that covered a good background on Amazon for a \
    range of stakeholders with different knowledge levels. It was clear, easy \
    to follow and some good take-aways for the team.\
  """
name = "Gabriella Egleton"
title = "Senior Brand Marketing Manager"
company = "Kervan Food UK"
image = "/images/GabriellaEgleton.png"
logo = "/images/brands/kervan.png"
