[[item]]
title = "#Amazon Advertising/PPC/DSP"
playlist_id = "PLIISXNQzZ8Zr98Hm9kmymGy9sQTdsiu-9"

[[item]]
title = "Become a great #Amazon Vendor"
playlist_id = "PLIISXNQzZ8ZqE2YJNP9mFPYw-OaIvz-rW"

[[item]]
title = "#Amazon SEO and Product Content Syndication"
playlist_id = "PLIISXNQzZ8ZpsC_wU3NQbtzNo5P2tbILy"

[[item]]
title = "Expand on #Amazon globally"
playlist_id = "PLIISXNQzZ8Zq5NvAvRy7fQm0Eem-i1xhO"

[[item]]
title = "#Amazon Sellers tools"
playlist_id = "PLIISXNQzZ8Zovq7HiGYpGgOa9TIBAcMlA"

[[item]]
title = "#e-Commerce Funding"
playlist_id = "PLIISXNQzZ8ZpOX_5uM8j0Xqs7morF1zX_"

[[item]]
title = "#Amazon FBA"
playlist_id = "PLIISXNQzZ8ZrSDPerYNXXMNJBvwvgAk2f"
