name: Deploy website

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  NODE_VERSION: v16.x

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # - run: sudo apt update && sudo apt install ffmpeg
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: docs
      - name: Cache npm dependencies
        id: cache-npm-libraries
        uses: actions/cache@v3
        with:
          path: .yarn/cache/*
          key: ${{ runner.os }}
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Install dependencies
        run: corepack yarn install --immutable
      - run: cd docs && git rm --ignore-unmatch -- *.svg *.html *.css *.js
      - name: Build website
        # Re-try several times in case there's a crash.
        run: corepack yarn build || corepack yarn build || corepack yarn build
      - name: Tweak Jekyll config for Base64Encoded file names
        run: cd docs && find . -regextype posix-extended -regex '.*_[^.]{42}\.[a-z]{3,4}' | awk '{ if (NR == 1) { print "include:" } print "  - " substr($0, 3) }' > _config.yml
      - name: Tweak Jekyll config to display future posts
        run: "cd docs && echo 'future: true' >> _config.yml"
      - name: Deploy
        run: |
          cd docs
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
